name: ci
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 下载 ABI 依赖
        env: { GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}" }
        run: ./ci/deps.sh
      - name: 构建
        run: make build
      - name: 测试
        run: make test
